[package]
name = "zksync-era-decompiler"
version = "0.1.0"
edition = "2024"

[dependencies]
zkevm_opcode_defs = "0.152.2"
serde = { version = "1.0.219", features = ["derive"] }
log = { version = "0.4.27", features = [] }
